version: '3.8'

services:
  app:
    image: datadiego808/hyperhash
    container_name: hyperhash_app
    environment:
      - NODE_ENV=production
      - COOKIE_SECRET=changethis
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: hyperhash_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

networks:
  default:
    driver: bridge