name: Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hyperhash:latest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build

#    steps:
#    - name: SSH to Linode and deploy
#      uses: appleboy/ssh-action@v0.1.3
#      with:
#        host: ${{ secrets.LINODE_HOST }}
#        username: ${{ secrets.LINODE_USERNAME }}
#        key: ${{ secrets.LINODE_SSH_KEY }}
#        script: |
#          docker pull ${{ secrets.DOCKER_USERNAME }}/hyperhash:latest
#          docker stop hyperhash || true
#          docker rm hyperhash || true
#          docker run -d --name hyperhash -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/hyperhash:latest